function [fitresult, gof] = createRC_Curve(DateTime, Voltage)
%CREATEFIT(DATETIME,VOLTAGE)
%  Create a fit.
%
%  Data for 'RC Model' fit:
%      X Input: DateTime from chargeData
%      Y Output: Voltage from chargeData
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jul-2026 16:16:50


%% Fit: 'RC Model'.
[xData, yData] = prepareCurveData( DateTime, Voltage );

% Set up fittype and options.
ft = fittype( '2.0326+(3.6-2.0326)*(1-exp(-x/tau))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.751267059305653;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'RC Model' );
h = plot( fitresult, xData, yData );
legend( h, 'Voltage vs. DateTime', 'RC Model', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'DateTime', 'Interpreter', 'none' );
ylabel( 'Voltage', 'Interpreter', 'none' );
grid on


